### PR TITLE
Add meta to GroupProps

### PR DESCRIPTION
**Pull request by AiusDa**
Since meta is not a declared prop in GroupProps interface when the prop is used in FieldControl the lint marks an error

### CODE REVIEW

**Comment by bietkul** [comment]
@AiusDa Thanks for figuring out this issue, I've already fixed it. Please update to the latest.

**Comment by AiusDa** [comment]
Hi @bietkul npm package is not yet updated.

**Comment by bietkul** [comment]
The latest version 1.0.23 has the updated code

**Comment by AiusDa** [comment]
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-reactive-form@^1.0.23
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cmm-front-react'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adrian/.npm/_logs/2018-05-22T21_37_51_047Z-debug.log
```

**Comment by bietkul** [comment]
Please try it now, there was some issue with the npm.

**Comment by AiusDa** [comment]
Thanks! now it's working!

**Pull request closed without merging**
